---
- name: CONFIGURE VLAN TO VNI MAPPING
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: "{{ item.vlan_id }}"
        mapped_vni: "{{ item.vni_id }}"
  with_items:
    - "{{ tenant1_vlans_l2vni }}"
    - "{{ tenant1_vlans_l3vni }}"

- name: CONFIGURE TENANT VRFs
  cisco.nxos.nxos_vrf:
    vrf: "{{ item.vrf }}"
    vni: "{{ item.vni_id }}"
    rd: auto
    state: present
  loop: "{{ tenant1_vrfs }}"

- name: CONFIGURE TENANT VRFs (cont'd)
  cisco.nxos.nxos_vrf_af:
    vrf: "{{ item.vrf }}"
    afi: ipv4
    route_target_both_auto_evpn: true
    state: present
  loop: "{{ tenant1_vrfs }}"

- name: CONFIGURE VXLAN VTEP NVE INTERFACE L2VNI MAPPING
  cisco.nxos.nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "{{ item.vni_id }}"
    multicast_group: "{{ item.mcast_grp }}"
  loop: "{{ tenant1_vlans_l2vni }}"

- name: CONFIGURE VXLAN VTEP NVE INTERFACE L3VNI MAPPING
  cisco.nxos.nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "{{ item.vni_id }}"
    assoc_vrf: true
  loop: "{{ tenant1_vlans_l3vni }}"

- name: CONFIGURE L2 EVPN VRFs
  cisco.nxos.nxos_evpn_vni:
    vni: "{{ item.vni_id }}"
    route_distinguisher: auto
    route_target_both: auto
  loop: "{{ tenant1_vlans_l2vni }}"

- name: CONFIGURE TENANT VRFs UNDER BGP PROCESS
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ asn }}"
      address_family:
        - afi: "{{ item.afi }}"
          safi: "{{ item.safi }}"
          vrf: "{{ item.vrf }}"
          advertise_l2vpn_evpn: true
  loop: "{{ tenant1_vrfs }}"

- name: CONFIGURE ANYCAST GW MAC
  cisco.nxos.nxos_overlay_global:
    anycast_gateway_mac: 1234.5678.9000

- name: CONFIGURE SVIs THAT ARE MAPPED TO VNIs
  cisco.nxos.nxos_interfaces:
    config:
      - name: Vlan{{ item.vlan_id }}
        enabled: true
  with_items:
    - "{{ tenant1_vlans_l2vni }}"
    - "{{ tenant1_vlans_l3vni }}"

- name: ASSOCIATE INTERFACES TO TENANT VRF
  cisco.nxos.nxos_vrf_interface:
    vrf: "{{ item.vrf }}"
    interface: vlan{{ item.vlan_id }}
  with_items:
    - "{{ tenant1_vlans_l2vni }}"
    - "{{ tenant1_vlans_l3vni }}"

- name: ENABLE ANYCAST GW UNDER L2VNI SVI
  cisco.nxos.nxos_interfaces:
    config:
      - name: Vlan{{ item.vlan_id }}
        fabric_forwarding_anycast_gateway: true
  loop: "{{ tenant1_vlans_l2vni }}"
- name: CONFIGURE IP FORWARD UNDER L3VNI SVI
  cisco.nxos.nxos_interfaces:
    config:
      - name: vlan{{ item.vlan_id }}
        ip_forward: true
  loop: "{{ tenant1_vlans_l3vni }}"

- name: CONFIGURE IP ADDRESS TO L2VNI SVI
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: Vlan{{ item.vlan_id }}
        ipv4:
          - address: "{{ item.addr }}/{{ item.mask }}"
  loop: "{{ tenant1_vlans_l2vni }}"

- name: CONFIGURE L2 INTERFACE
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        enabled: true
        mode: layer2
  with_items:
    - "{{ tenant1_l2_access }}"
    - "{{ tenant1_l2_trunk }}"

- name: CONFIGURE VLAN ACCESS
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "{{ item.interface }}"
        access:
          vlan: 11
  loop: "{{ tenant1_l2_access }}"

- name: CONFIGURE VLAN TRUNK
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "{{ item.interface }}"
        trunk:
          allowed_vlans: 10,12-15
  loop: "{{ tenant1_l2_trunk }}"
