---
- name: ENABLE FEATURES
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
  loop: "{{ leaf_features }}"

- name: ENABLE OSPF PROCESS
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: "{{ ospf_process_id }}"
          router_id: "{{ router_id }}"
          areas:
            - area_id: 0.0.0.0
              default_cost: 10

- name: CONFIGURE LOOPBACK INTERFACES
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        enabled: true
  loop: "{{ loopbacks }}"

- name: CONFIGURE LOOPBACK IP ADDR
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        ipv4:
          - address: "{{ item.addr }}"
  loop: "{{ loopbacks }}"

- name: ASSOCIATE LOOPBACK WITH OSPF PROCESS
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            processes:
              - process_id: "{{ ospf_process_id }}"
                area:
                  area_id: "{{ ospf_area }}"
  loop: "{{ loopbacks }}"

- name: CONFIGURE LINK INTERFACES
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        enabled: true
        mode: layer3
  loop: "{{ interfaces }}"

- name: CONFIGURE INTERFACE IP OSPF
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        ipv4:
          - address: "{{ item.addr }}"
  loop: "{{ interfaces }}"

- name: ASSOCIATE INTERFACE WITH OSPF PROCESS
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            network: point-to-point
            processes:
              - process_id: "{{ ospf_process_id }}"
                area:
                  area_id: "{{ ospf_area }}"
  loop: "{{ interfaces }}"

- name: ENABLE NV OVERLAY EVPN
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true

- name: CONFIGURE BGP ASN, ROUTER ID, AND NEIGHBORS
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ asn }}"
      router_id: "{{ router_id }}"
      neighbors:
        - neighbor_address: "{{ item.neighbor }}"
          remote_as: "{{ item.remote_as }}"
          update_source: "{{ item.update_source }}"
  loop: "{{ leaf_bgp_neighbors }}"

- name: CONFIGURE BGP NEIGHBOR AFI, SAFI, COMMUNITY, and RR
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ asn }}"
      neighbors:
        - neighbor_address: "{{ item.neighbor }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: true
              route_reflector_client: true
  loop: "{{ leaf_bgp_neighbors }}"

# - name: CONFIGURE VLAN TO VNI MAPPING
#   cisco.nxos.nxos_vlans:
#     config:
#       - vlan_id: "{{ item.vlan_id }}"
#         mapped_vni: "{{ item.vni_id }}"
#   with_items:
#     - "{{ leaf_vlans_l2vni }}"
#     - "{{ leaf_vlans_l3vni }}"

# - name: CONFIGURE TENANT VRFs
#   cisco.nxos.nxos_vrf:
#     vrf: "{{ item.vrf }}"
#     vni: "{{ item.vni_id }}"
#     rd: auto
#     state: present
#   loop: "{{ leaf_vrfs }}"

# - name: CONFIGURE TENANT VRFs (cont'd)
#   cisco.nxos.nxos_vrf_af:
#     vrf: "{{ item.vrf }}"
#     afi: ipv4
#     route_target_both_auto_evpn: true
#     state: present
#   loop: "{{ leaf_vrfs }}"

- name: CONFIGURE VXLAN VTEP NVE INTERFACE
  cisco.nxos.nxos_interfaces:
    config:
      - name: nve1
        enabled: true
    state: merged

- name: CONFIGURE VXLAN VTEP NVE INTERFACE FOR EVPN CONTROL PLANE
  cisco.nxos.nxos_vxlan_vtep:
    interface: nve1
    host_reachability: true
    source_interface: Loopback1
    state: present

- name: SAVE RUN CONFIG TO STARTUP CONFIG
  cisco.nxos.nxos_config:
    save_when: always
