---
vrf: prod
vni_id: 1000
vlans_l3vni:
  - { vlan_id: 100, vni_id: 1000 }
vlans_l2vni:
  - { vlan_id: 101, vni_id: 1101, addr: 10.1.1.1/24 }
  - { vlan_id: 102, vni_id: 1102, addr: 10.1.2.1/24 }
  - { vlan_id: 103, vni_id: 1103, addr: 10.1.3.1/24 } 
  - { vlan_id: 104, vni_id: 1104, addr: 10.1.4.1/24 }
  - { vlan_id: 105, vni_id: 1105, addr: 10.1.105.1/24 }
l2_access:
  - { interface: Ethernet1/4, vlan_id: 100 }
l2_trunk:
  - { interface: Ethernet1/5, vlan_id: 101-104 }
