---
router_id: 10.10.10.22
loopbacks:
  - interface: Loopback0
    addr: 10.10.10.22/32
  - interface: Loopback1
    addr: 2.2.2.2/32
interfaces:
  - interface: Ethernet1/1
    addr: 172.12.0.3/31