router_id: 10.10.10.22

loopbacks:
- { interface: loopback0, addr: 10.10.10.22, mask: 32 }
- { interface: loopback1, addr: 2.2.2.2, mask: 32 }

interfaces:
- { interface: Ethernet1/1, addr: 172.12.0.3, mask: 31 }